---
- name: Converge
  hosts: all
  become: true
  vars:
    kata_containers_enabled: true
    container_manager: containerd
  roles:
    - role: kubespray_defaults
    - role: container_engine/containerd
    - role: container_engine/kata-containers
