# noqa role-name - this is a meta role that doesn't need a name
---
dependencies:
  - role: container_engine/validate-container_engine
    tags:
      - container_engine
      - validate-container_engine

  - role: container_engine/kata-containers
    when:
      - kata_containers_enabled
    tags:
      - container_engine
      - kata-containers

  - role: container_engine/gvisor
    when:
      - gvisor_enabled
      - container_manager in ['docker', 'containerd']
    tags:
      - container_engine
      - gvisor

  - role: container_engine/crun
    when:
      - crun_enabled
    tags:
      - container_engine
      - crun

  - role: container_engine/youki
    when:
      - youki_enabled
      - container_manager == 'crio'
    tags:
      - container_engine
      - youki

  - role: container_engine/cri_o
    when:
      - container_manager == 'crio'
    tags:
      - container_engine
      - crio

  - role: container_engine/containerd
    when:
      - container_manager == 'containerd'
    tags:
      - container_engine
      - containerd

  - role: container_engine/cri_dockerd
    when:
      - container_manager == 'docker'
    tags:
      - container_engine
      - docker
