---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: bastion_ssh_config
  tasks:
    - name: Copy config to remote host
      copy:
        src: "{{ playbook_dir }}/{{ ssh_bastion_confing__name }}"
        dest: "{{ ssh_bastion_confing__name }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
